---

- name: Install Homebrew packages
  homebrew_cask:
    name:
      - utm
      - alacritty
      - 1password
      - firefox
      - google-chrome
      - notion
      - rectangle
    state: present
    accept_external_apps: true
  when: ansible_facts["os_family"] == "Darwin" 
