---

- name: Install asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    version: v0.18.0
    dest: "{{ lookup('env', 'HOME') }}/.asdf"
    update: yes

- name: Run Make
  command: make
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.asdf"

- name: Copy asdf binary into $PATH
  become: true
  command: cp asdf /usr/local/bin
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.asdf"

- name: Install asdf plugins
  command: "{{ lookup('env', 'HOME') }}/.asdf/bin/asdf plugin-add {{ item }}"
  with_items:
    - erlang
    - elixir
    - golang
    - nodejs
    - ruby
    - rust
  ignore_errors: true
