---

- name: Install asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    version: v0.9.0
    dest: "{{ lookup('env', 'HOME') }}/.asdf"
    update: yes

- name: Install asdf plugins
  command: "{{ lookup('env', 'HOME') }}/.asdf/bin/asdf plugin-add {{ item }}"
  with_items:
    - erlang
    - elixir
    - golang
    - nodejs
    - ruby
    - rust
  ignore_errors: true
