---

- name: Install Homebrew casks
  homebrew_cask:
    name:
      - imageoptim
    state: present
    accept_external_apps: true
  when: ansible_facts["os_family"] == "Darwin" 

- name: Include package vars
  include_vars: 'packages.yml'

- name: Install packages
  become: "{{ ansible_system == 'Linux' }}"
  package:
    name: "{{ family_with_default }}"
    state: present

- import_tasks: dotfiles.yml
- import_tasks: vim.yml
- import_tasks: asdf.yml
- import_tasks: tailscale.yml
